# Generated by Django 6.0.4 on 2026-05-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
