# Generated by Django 6.0.4 on 2026-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_contentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
