# Generated by Django 6.0.4 on 2026-05-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCourseExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='courses.course')),
                ('excluded_chapters', models.ManyToManyField(blank=True, related_name='exclusions_as_chapter', to='courses.chapter')),
                ('excluded_contents', models.ManyToManyField(blank=True, related_name='exclusions_as_content', to='courses.content')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='courses.coursepackage')),
            ],
            options={
                'unique_together': {('package', 'course')},
            },
        ),
    ]
