# Generated by Django 6.0.4 on 2026-05-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_packagecourseexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='groups', to='courses.coursepackage'),
        ),
    ]
