# Generated by Django 6.0.4 on 2026-05-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_faceaccesslog_userface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userface',
            name='image',
        ),
        migrations.AddField(
            model_name='userface',
            name='embedding',
            field=models.JSONField(default=list),
        ),
    ]
